#!/bin/sh

CRONTAB_FILE="/etc/crontab"

if [ ! -x $BACKUP_DISABLED ]; then
  echo "Database backup is disabled."
  exit 1
fi


echo SHELL=/bin/bash > $CRONTAB_FILE
echo PATH=$PATH >> $CRONTAB_FILE
cat /etc/crontab.schedule >> $CRONTAB_FILE
echo  >> $CRONTAB_FILE

exec /usr/sbin/cron -f
