#!/bin/sh

CRONTAB_FILE="/etc/crontab"

if [ ! -x $BACKUP_DISABLED ]; then
  echo "Database backup is disabled."
  exit 1
fi



cat <<EOF > $CRONTAB_FILE
SHELL=/bin/bash
PATH=$PATH
MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
AWS_ACCESS_KEY=$AWS_ACCESS_KEY
AWS_SECRET_KEY=$AWS_SECRET_KEY
EOF

cat /etc/crontab.schedule  >> $CRONTAB_FILE

exec /usr/sbin/cron -f
