#!/bin/sh

echo "Transfering backup to S3 bucket"

configure_s3cfg() {
  egrep "^(access_key|secret_key)" /root/.s3cfg
  if [ $? -ne 0 ] ; then
    echo "access_key = $AWS_ACCESS_KEY" >> /root/.s3cfg
    echo "secret_key = $AWS_SECRET_KEY" >> /root/.s3cfg
  fi
}

perform_backup() {
  :
}

copy_to_s3() {
  :
}

delete_backup() {
  :
}

configure_s3cfg && copy_to_s3 && delete_backup
